name = "webapp"
compatibility_date = "2026-01-31"
pages_build_output_dir = "./dist"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "18d17ca5b3034b2087a9b7c0afe19efd"

[[d1_databases]]
binding = "DB"
database_name = "kia-accessories-db"
database_id = "eb874b09-6806-4f5a-9183-b828b7f91e5f"

[[r2_buckets]]
binding = "R2"
bucket_name = "kia-accessories-images"
